[project]
name = 'nginx-conf'
channels = ['conda-forge']
platforms = ['linux-64', 'osx-64', 'osx-arm64', 'win-64']

[dependencies]
pandas = '>=2.1.1'
pooch = '>=1.8.1'
pydantic-settings = '>=2.3.0'
python = '>=3.12.0'
rich = '>=9.12.0'
tqdm = '>=4.56.0'
